name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install the Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          # Add the wasm target for cargo build
          targets: wasm32-unknown-unknown
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Run tests
      run: cargo test --verbose  
    - name: Copy files to artifact directory
        # Copy the necessary files for the website to run
      run: |
          mkdir dist
          cp src/index.html dist/
          cp target/wasm32-unknown-unknown/release/web_terminal_rs.wasm dist/
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
            path: ${{github.workspace}}/dist/ 
